import pyrosetta
from pyrosetta import *

import numpy as np

def create_scoring_function():

	cen_sfxn = ScoreFunction()

	# Expanded Rosetta terms
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_atr, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_rep, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_sol, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_intra_sol_xover4, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_ball_wtd, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_intra_rep, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.pro_close, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hbond_sr_bb, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hbond_lr_bb, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hbond_bb_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hbond_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.dslf_fa13, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.rama_prepro, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.omega, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.p_aa_pp, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_dun, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.yhh_planarity, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.ref, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_intra_atr, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_intra_sol, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_ball, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_ball_iso, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hbond, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_lj_intra_rep, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_lj_intra_atr, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_lj_inter_rep, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_lj_inter_atr, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_twist, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_bend, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.mm_stretch, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_costheta, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_polar, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.lk_nonpolar, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec_bb_bb, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec_bb_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec_sc_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.peptide_bond, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.pcs2, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cen_pair_motifs, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec_aro_aro, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_elec_aro_all, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.ch_bond, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.ch_bond_bb_bb, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.ch_bond_sc_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.ch_bond_bb_sc, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.rama2b, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cenpack, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cenpack_smooth, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.gauss, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_pair_aro_aro, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_pair_aro_pol, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_pair_pol_pol, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.occ_sol_exact, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.pair, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cen_pair_smooth, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.interchain_pair, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.interchain_vdw, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.gb_elec, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.envsmooth, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cen_env_smooth, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cbeta_smooth, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.env, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cbeta, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.DFIRE, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.rg, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.sa, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cart_bonded, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cart_bonded_angle, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.cart_bonded_length, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.neigh_vect, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.neigh_count, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.neigh_vect_raw, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.interface_dd_pair, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.goap, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.goap_dist, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.goap_angle, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.pack_stat, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.surface, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.hpatch, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_dun_dev, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_dun_rot, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.fa_dun_semi, 1.0)
	cen_sfxn.set_weight(pyrosetta.rosetta.core.scoring.co, 1.0)

	return cen_sfxn

def extract_pairwise_scores(energy_map):

	pairwise_score_list = []

	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_atr))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_rep))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_sol))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_intra_sol_xover4))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_ball_wtd))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_intra_rep))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.pro_close))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hbond_sr_bb))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hbond_lr_bb))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hbond_bb_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hbond_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.dslf_fa13))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.rama_prepro))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.omega))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.p_aa_pp))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_dun))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.yhh_planarity))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.ref))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_intra_atr))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_intra_sol))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_ball))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_ball_iso))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hbond))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_lj_intra_rep))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_lj_intra_atr))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_lj_inter_rep))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_lj_inter_atr))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_twist))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_bend))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.mm_stretch))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_costheta))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_polar))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.lk_nonpolar))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec_bb_bb))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec_bb_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec_sc_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.peptide_bond))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.pcs2))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cen_pair_motifs))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec_aro_aro))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_elec_aro_all))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.ch_bond))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.ch_bond_bb_bb))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.ch_bond_sc_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.ch_bond_bb_sc))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.rama2b))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cenpack))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cenpack_smooth))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.gauss))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_pair_aro_aro))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_pair_aro_pol))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_pair_pol_pol))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.occ_sol_exact))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.pair))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cen_pair_smooth))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.interchain_pair))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.interchain_vdw))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.gb_elec))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.envsmooth))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cen_env_smooth))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cbeta_smooth))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.env))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cbeta))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.DFIRE))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.rg))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.sa))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cart_bonded))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cart_bonded_angle))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.cart_bonded_length))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.neigh_vect))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.neigh_count))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.neigh_vect_raw))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.interface_dd_pair))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.goap))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.goap_dist))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.goap_angle))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.pack_stat))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.surface))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.hpatch))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_dun_dev))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_dun_rot))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.fa_dun_semi))
	pairwise_score_list.append(energy_map.get(pyrosetta.rosetta.core.scoring.co))

	return np.array(pairwise_score_list)